services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:5000/api/v1
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - MongoDb__ConnectionString=${MONGODB_CONNECTION_STRING}
      - MongoDb__DatabaseName=${MONGODB_DATABASE_NAME}
